version: "3.8"
services:
  db:
    build: ./app/dbScripts
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: P@ssword12
      MYSQL_DATABASE: tasks
    restart: always
  web:
    build: ./app
    environment:
      MYSQL_DATABASE: tasks
      MYSQL_USER: root
      MYSQL_PASSWORD: P@ssword12
      MYSQL_HOST: db
    ports:
      - "4000:4000"
    depends_on:
      - db
    restart: on-failure