version: "3.8"
services:
  db:
    build: ./app/dbScripts
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    restart: always
  web:
    build: ./app
    environment:
      DB_NAME: $MYSQL_DATABASE
      DB_USER: $MYSQLDB_USER
      DB_PASSWORD: $MYSQL_PASSWORD
      DB_HOST: $MYSQL_HOST
    ports:
      - "4000:4000"
    depends_on:
      - db
    restart: on-failure